---
- hosts: cluster
  remote_user: ezzie
  tasks:
  - name: delete deployment file to K8 master
    file:
      dest: /home/ezzie/nginx-deployment.yaml
      state: absent 
  - name: copying new deployment file to K8 master
    copy:
      src: /etc/ansible/ansible-playbook/nginx-deployment.yaml
      dest: /home/ezzie/
  - name: deploying the pod into the cluster
    command: kubectl apply -f nginx-deployment.yaml